# Ship a minimal metadata file that can be picked up by Streamlit at runtime.
[project]
name = "st_aggrid"
version = "2.0.0.rc1"

[[tool.streamlit.component.components]]
name = "agGrid"
asset_dir = "frontend/build"
