[tool.poetry]
name = "streamlit-aggrid"
version = "0.2.2-3"
description = "Streamlit component implementation of ag-grid"
classifiers = ["Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent"]
homepage = "https://github.com/PablocFonseca/streamlit-aggrid"
authors = ["Pablo Fonseca <pablo.fonseca+pip@gmail.com>"]
readme = "README.md"
exclude = ["**/node_modules/**/*", "**/frontend/src/**/*"]
include = ["**/frontend/build/**/*"]
packages = [{include="st_aggrid"}]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
streamlit = ">=0.87.0"
pandas = ">=1.2"
simplejson = ">=3.0"
python-dotenv = "^0.19.1"

[build-system]  
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

