[tool.poetry]
name = "streamlit-aggrid"
version = "0.3.5"
description = "Streamlit component implementation of ag-grid"
classifiers = ["Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent"]
homepage = "https://github.com/PablocFonseca/streamlit-aggrid"
authors = ["Pablo Fonseca <pablo.fonseca+pip@gmail.com>"]
readme = "README.md"
exclude = ["**/node_modules/**/*", "**/frontend/src/**/*", "**/.yarn/**/*"]
include = ["**/frontend/build/**/*"]
packages = [{include="st_aggrid"}]

[tool.poetry.dependencies]
python = ">=3.8, !=3.9.7"
streamlit = ">=0.87.0"
pandas = ">=1.2"
python-decouple = "^3.6"
altair = "<5"

[tool.poetry.dev-dependencies]
black = "*"
watchdog = "^2.1.9"

[build-system]  
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api" 

